<?php
$skinsname="phptpl模板";
$skinsauthor="官网模板";
$skinsversion="v1.0";
$skinsauthorsite="http://www.deitui.com";
$skinstype="pc";
$skinsinfo="产品分类：skins_procat,资讯分类:skins_artcat";
$skinsdir="phptpl";
$skinsprice="0";
$skinsdata=array(
	"skins_procat"=>1,
	"skins_artcat"=>7
);
?>